export const ACCOUNT = {
  ERROR: 'ACCOUNT_ERROR',
  GET: 'ACCOUNT_GET',
  GET_ONE_LOADING: 'ACCOUNT_GET_ONE_LOADING',
  GET_ALL: 'ACCOUNT_GET_ALL',
  SET_LOADING: 'ACCOUNT_SET_LOADING',
  TOKEN_CLEAR: 'ACCOUNT_TOKEN_CLEAR',
  TOKEN_SET: 'ACCOUNT_TOKEN_SET',
};
export const AUTH = {
  LOAD_USER_FAIL: 'AUTH_LOAD_USER_FAIL',
  LOAD_USER_SUCCESS: 'AUTH_LOAD_USER_SUCCESS',
  LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGOUT: 'AUTH_LOGOUT',
  SET_LOADING: 'AUTH_SET_LOADING',
};
export const PRODUCT = {
  CLEAR_ALL: 'PRODUCT_CLEAR_ALL',
  CURRENT_CLEAR: 'PRODUCT_CURRENT_CLEAR',
  CURRENT_SET: 'PRODUCT_CURRENT_SET',
  DELETE: 'PRODUCT_DELETE',
  ERROR: 'PRODUCT_ERROR',
  GET_ALL: 'PRODUCT_GET_ALL',
  SET_LOADING: 'PRODUCT_SET_LOADING',
  UPDATE_FAIL: 'PRODCUT_UPDATE_FAIL',
  UPDATE_RESET: 'PRODUCT_UPDATE_RESET',
  UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
};
export const TRANSACTION = {
  ADD_SUCCESS: 'TRANSACTION_ADD_SUCCESS',
  ERROR: 'TRANSACTION_ERROR',
  GET_ALL: 'TRANSACTION_GET_ALL',
  RESET: 'TRANSACTION_RESET',
  SET_LOADING: 'TRANSACTION_SET_LOADING',
};
