export const ACCOUNT = {
  GET_ALL: 'ACCOUNT_GET_ALL',
};
export const AUTH = {
  LOAD_USER_FAIL: 'AUTH_LOAD_USER_FAIL',
  LOAD_USER_SUCCESS: 'AUTH_LOAD_USER_SUCCESS',
  LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGOUT: 'AUTH_LOGOUT',
};
export const TRANSACTION = {
  ERROR: 'TRANSACTION_ERROR',
  GET_ALL: 'TRANSACTION_GET_ALL',
  SET_LOADING: 'TRANSACTION_SET_LOADING',
};
export const SET_LOADING = 'SET_LOADING';
